### ISSUE TITLE
Create a percentage value on the alert-response page

### ISSUE THREAD

**Issue by nerdyness** [bulletproofnetworks/pigeonhole#14]
Two of the values [asked for by execs](https://wiki.bulletproof.net/display/clouddev/2015/03/13/Cloud+Development+goals) are

* 95th percentile time to acknowledge alert
* % of monitoring alerts acknowledged within 60 seconds

Could we get that integrated and displayed on the [alert-response](http://pigeonhole.production.maint.bulletproof.net/alert-response/) page?

Ping me for any questions.

**Comment by Hobbsee** [comment]
I'd like to see this on the front page, instead of categorisation - it seems like a logical first thing to show.

**Comment by davesharpe9** [comment]
@Hobbsee +1.  Additionally - aggregated into Confluence, since thats the only tool an Exec will use with any consistency.

**Comment by nerdyness** [comment]
@Hobbsee agreed! alert-response should be the first page to load.

@davesharpe9 aggregated into Confluence? How is this meant to look? Could you elaborate?

**Comment by Hobbsee** [comment]
I have a bunch of in-progress thoughts about how this should be done.

I've discussed this with Katie, and I'll do a write-up / basic code up of those thoughts, and @glasnt can pretty it up / check it over.

Initial code on https://github.com/bulletproofnetworks/pigeonhole/tree/index-page

**Comment by Hobbsee** [comment]
Right, there's now some code with a couple of FIXMEs to get the mean / deviation / 95th percentile of both acknowledgements and resolves in the last 24 hours, and over the last complete 3 8 hour shifts, as well as the one currently running.

This data needs sanity checking [1] and prettifying, and the FIXMEs to be fixed.  All times are currently in seconds.  I'll add in the % of monitoring alerts acknowledged within 60 seconds tomorrow.

[1] This doesn't match what is on the alert-response page, as the latter excludes things without an incident key, which wouldn't make much sense to display.

**Comment by Hobbsee** [comment]
> I'll add in the % of monitoring alerts acknowledged within 60 seconds tomorrow.

This is done, but these numbers are extremely low. Maybe we also need to add acks within 2 minutes.

**Comment by nerdyness** [comment]
> Maybe we also need to add acks within 2 minutes.

Our SLA to ACK/respond to alerts is 5 minutes. That would be another interesting value to track. Execs have asked for 60 seconds but we can probably add more. Shouldn't be too hard to have a variable threshold of 60/120/300 seconds.

**Comment by glasnt** [comment]
Pretty sure #31 and a few others resolve this.
