### ISSUE TITLE
Create ro/rw user roles

### ISSUE THREAD

**Issue by nerdyness** [bulletproofnetworks/pigeonhole#15]
See https://github.com/bulletproofnetworks/pigeonhole/pull/9:

> > As an aside, what sanitising do we need to do here?

> Any destructive instructions I guess. DELETE from timeseries; and the like.
> 
> We could seriously minimise damage if we allowed for a read-only user and a more privileged read/write user here. The import script uses the read/write user and hitting submit on the categorisation page opens a new influx connection using the read/write user credentials. Everything else, especially the search runs as the read-only user.
>
> So the worst we'd have to fear is that somebody runs a select * from timeseries; and gets all information they could have queried anyway :smile:

**Comment by Hobbsee** [comment]
Password is TqwtXBVsjqpUxH5r6tQ2

hubot-lore ➤ curl http://bpsyd07-dvmh-rndutils-01.inf.bulletproof.net:8086/db/pigeonhole_production/users\?u\=root\&p\=root | json_pp                                                                                            (master|…)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142  100   142    0     0   1675      0 --:--:-- --:--:-- --:--:--  1670
[
   {
      "writeTo" : ".*",
      "name" : "pigeonhole",
      "readFrom" : ".*",
      "isAdmin" : false
   },
   {
      "readFrom" : ".*",
      "name" : "pigeonhole_ro",
      "writeTo" : "^$",
      "isAdmin" : false
   }
]

**Comment by Hobbsee** [comment]
Sent the new password to you, @glasnt

**Comment by Hobbsee** [comment]
This is done and deployed.
