### ISSUE TITLE
Line graph for number of alerts per 1 hour is incorrect

### ISSUE THREAD

**Issue by Hobbsee** [bulletproofnetworks/pigeonhole#26]
As shown below, the line graph keeps dropping to 0 for every point, even though there's non-zero data for every point.

![screen shot 2015-05-14 at 7 27 57 pm](https://cloud.githubusercontent.com/assets/3038925/7629416/a7ce8194-fa6f-11e4-9599-3cd9255f4b84.png)

**Comment by nerdyness** [comment]
I just browsed to [pigeonhole](http://pigeonhole.production.maint.bulletproof.net/alert-response/) and it looks as expected 
![screenshot-pigeonhole - mozilla firefox](https://cloud.githubusercontent.com/assets/696600/7643840/74e1d5d0-fae0-11e4-8d58-7b484e03bcf9.png)

Selecting yesterday && today as the date range changed this:
![screenshot-pigeonhole - mozilla firefox-1](https://cloud.githubusercontent.com/assets/696600/7643855/b4783568-fae0-11e4-88c9-2e189337efbe.png)

Looking a bit further

**Comment by nerdyness** [comment]
Looking at `@series` [here](https://github.com/bulletproofnetworks/pigeonhole/blob/master/pigeonhole.rb#L76), if I load one day I get:

```
"[{\"name\":\"Number of alerts per 1h\",\"data\":[[1431612000000,0],[1431615600000,0],[1431619200000,4],[1431622800000,2]...
```

If I load more than one day the data contains 2 values for each timestamp: "0" and then the actual value:
```
"[{\"name\":\"Number of alerts per 1h\",\"data\"[[1431525600000,0],[1431525600000,3],[1431529200000,0],[1431529200000,4],[1431532800000,0],[1431532800000,2]:(..)[1431615600000,0],[1431615600000,0],[1431619200000,0],[1431619200000,4],(..)
```

**Comment by nerdyness** [comment]
Turns out influxdb returns the data we display:
```
:count=>[{"time"=>1431565200, "count"=>19}, {"time"=>1431561600, "count"=>18},(..),{"time"=>1431561600, "count"=>0}, {"time"=>1431565200, "count"=>0},(..)
```

**Comment by nerdyness** [comment]
I can't even.

`select count(incident_key) from pigeonhole where time > 1431525600s and time < 1431662482s group by time(1h) fill(0)`
returns duplicates, while
`select count(incident_key) from pigeonhole group by time(1h), fill(0) where time > 1431525600s and time < 1431662421s` doesn't.

Looking at the [query_language](http://influxdb.com/docs/v0.8/api/query_language.html) the latter is the preferred syntax. PR coming up.

**Comment by nerdyness** [comment]
https://github.com/influxdb/influxdb/issues/2583
