### ISSUE TITLE
Does it make sense to create a version

### ISSUE THREAD

**Issue by nerdyness** [bulletproofnetworks/pigeonhole#33]
As per our discussion prior to DevOps days in Melbourne, does it make sense to version pigeonhole since it's a public project?

/cc @glasnt @SarahKowalik

**Comment by glasnt** [comment]
Yes, it does make sense. Especially when we change the format of the configuration file in a breaking manner. 

I suggest using github releases and semver. Unsure if we want to include the version on the running app or not.

**Comment by SarahKowalik** [comment]
Yep, do it.

**Comment by glasnt** [comment]
See PR #35
