### ISSUE TITLE
Make the date string more persistent

### ISSUE THREAD

**Issue by nerdyness** [bulletproofnetworks/pigeonhole#4]
Put the selected dates in the query string so switching the tabs on the top keeps the same dates rather than resetting to today.

"alert-frequency?from=2015-03-08&to=2015-04-08
you should be able to then just tack on the params to the urls generated for the nav links in the header
$query_string or some such"

**Comment by nerdyness** [comment]
This will also be super-handy for rianna.

**Comment by glasnt** [comment]
Totes fixed in #6
