### ISSUE TITLE
Shifts documentation

### ISSUE THREAD

**Issue by jaxxstorm** [bulletproofnetworks/pigeonhole#40]
The shifts part of config.toml.example isn't immediately clear to me. Is there any chance we can get some documentation on what it does?

**Comment by nerdyness** [comment]
Hi @jaxxstorm, apologies for the delay on this. I was on leave and am currently the only person looking after this.

Our support team of our Sydey based company has a follow the sun principle. So during the week we run 3 x 8 hour shifts. The first shift starting in Sydney, Australia; the 2nd in South Africa; and the 3rd in the USA.

To gauge how many resources we need in which timezone by looking at the distribution of alerts we split up the data in pigeonhole into 3 shifts and compare them against each other. I hope this helps for now. Let me know if you have any further questions!

**Comment by jaxxstorm** [comment]
Works for me, thanks!
