### ISSUE TITLE
Create a search page

### ISSUE THREAD

**Issue by nerdyness** [bulletproofnetworks/pigeonhole#5]
At the top of the page is a search field that lets you search for
* entity
* check
* entity & check

Ideally the search bar is displayed in the navbar at all times. Submitting a search query takes you to the search page.

- Link to the search from the list of top noise candidates. One click on the top-alert takes you to the search results page
- The search results page shows the amount of times the alert fired
- display whatever other awesome things come to mind

**Comment by glasnt** [comment]
See #9
